### PR TITLE
HPC Carpentry breakout session

### PR DESCRIPTION
**Pull request by ocaisa**
While I think this is probably dense for an hour slot, it's a start.

Ideally, I would like to narrow the scope of the session so that we can ensure we get to identify short term goals and people to make them happen by the end of the session. For that reason it would be really helpful if all those who've been involved to date help out with this abstract (and the approach) to help do the narrowing:  @ChristinaLK @psteinb @dgasmith @aturner-epcc @bernhold (please tag others too if you think it's a good idea).

In particular, we want to try and ensure that we help define goals that are constructive for the workshop the next day.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Part 2 has already been done in multiple forums and seems a bit redundant, seeing that there's already developed materials.  I think a better goal would be what to do next with the materials that already exist, in cooperation w/ compute canada.

**Comment by ChristinaLK** [comment]
Also, we could add slack, but there's an existing hpc-discuss list, so we don't need another mailing list.

**Comment by ocaisa** [comment]
@ChristinaLK With respect to Part 2, can you be a bit more specific as to what you consider done? Are you saying that we should look as far as the HPC novice lesson and no further, and then just look into finalising a lesson for the existing material?

Finalising a novice lesson in the Workshop the next day is a sensible goal, in the breakout session I think we can afford to also entertain other topics (especially since there are many that may not have been part of previous discussions).

**Comment by ocaisa** [comment]
Also, the topics I jotted down were just suggestions, I'm open to changing them, especially if you think they're already covered by the BoF output (which will have been reviewed by that point).

**Comment by ChristinaLK** [comment]
@ocaisa the questions you listed: 
- Can we agree a scope and target group for an initial HPC novice lesson?
- How do we approach access to HPC resources, is it just assumed to be available?
- How do we make lessons flexible wrt *scheduler, environment, access,...*?
- How far could/should HPC Carpentry go?

I think we already have tentative answers to these, based on previous conversations, in addition to actual curricula that (implicitly) answer them.  Instead of an open discussion, I think it would be more productive to present the answers we already have and then have people evaluate -- where do they most significantly agree, disagree, etc.  That gives us a good starting point for next steps because we're starting with what we already have.

**Comment by ocaisa** [comment]
Ok, so I take from that we might be better served by spending more time covering pre-existing discussions (summarising the BoF output and the issues in hpc-novice say, the mailing list is not too active)? I can reorganise things to suit that.

What about 20 mins for that and 5 each for the two lightning talks on the novice lessons that are in the wild?

I'll have another think about the final 30 then. I feel like there is a lot in the HPC space that serves to distort the collaborativeness of the effort: it's not like we can all condense around a given scheduler, module environment etc. This can mean a lot of lesson tweaking for the instructor that could easily end up with people developing/maintaining their own forks rather than collaborating on a shared lesson. I take the point of @dgasmith in this context, it is one thing to get the people in the room, but how do we keep them talking afterwards (particularly after `hpc-novice v1.0`)?

**Comment by ChristinaLK** [comment]
I like the 20 minutes for reviewing / honing discussions + 10 minutes of reviewing the two available materials.  

Honestly, if we could have lesson infrastructure in place *by* Carpentry Con that could be customized for various schedulers, then that would be a great starting point -- building out examples in slurm, pbs, etc.

**Comment by ocaisa** [comment]
@aturner-epcc If you are willing to commit to working on it that would be great. In https://github.com/swcarpentry/hpc-novice/issues/12 @psteinb suggested it could be done with a pandoc filter and the [SLURM rosetta table](https://slurm.schedmd.com/rosetta.pdf) should have all we need for simple stuff.

For the scheduler in particular we could also automatically generate any required job scripts based on a configuration file provided by the end user. I've used the python module [GC3Pie](https://gc3pie.readthedocs.io/en/master/) a little in the past and it supports lsf, pbs, sge and slurm. I'm pretty sure we can just get it to dump the job scripts.

**Comment by ocaisa** [comment]
If there are no more comments then I think this can be merged @fpsom

**Comment by ocaisa** [comment]
@dgasmith Can you add your bio, the included link for you is dead until that's merged.

**Comment by dgasmith** [comment]
@ocaisa Done!

**Comment by psteinb** [comment]
Sorry for coming late to the party. Regarding the issue of different schedulers, [hpc-in-a-day](https://github.com/psteinb/hpc-in-a-day#scheduler) has solved this with jekyll. The idea (not very elegant but functional) is that code snippets are not inlined in the markdown. They are rather contained in dedicated files which have a suffix identical to the scheduler acronym. Here is what the markdown looks like:

```
~~~
{% include /snippets/02/submit_hello_world_to_void.{{ site.workshop_scheduler }} %}
~~~
{: .bash}
```

and `snippets/02/` contains:

```
$ ls submit_hello_world_to_void*
submit_hello_world_to_void.lsf  submit_hello_world_to_void.slurm
```
Any suggestions beyond this very simple recipe are highly welcome. ;)

**Comment by psteinb** [comment]
on the discussion of the agenda: I agree with @ChristinaLK that the session should focus on the status quo and bringing together those interested. The time frame barely supports anything else in my opinion.

**Comment by ocaisa** [comment]
@malvikasharan I had a go, let me know if you that's ok

**Comment by aturner-epcc** [comment]
@psteinb That looks like a good solution to me.

My other thought for something useful that I could prepare to help the session at CarpentryCon is an episode-by-episode comparison between hpc-novice (from @psteinb) and hpc-intro from Compute Canada. This would hopefully help inform discussion on next steps.

**Comment by fpsom** [comment]
Thanks @ocaisa @dgasmith @ChristinaLK @aturner-epcc @psteinb for this discussion and the content! Really awesome work!

**Comment by ocaisa** [comment]
Sounds useful, @psteinb has been involved in this chain but I'm not sure @jstaf (from https://github.com/hpc-carpentry/ ) is aware of this discussion (yet).

**Comment by aturner-epcc** [comment]
@ocaisa @psteinb @jstaf @ChristinaLK  Not sure if this is the correct place to put this (happy for suggestions of better places)! Here is the brief comparison of the two existing lessons with the topic lists from the SC17 BoF. Hopefully this will be useful in providing information to launch discussions of were we go next.

[HPCCarpentry_Comparison.pdf](https://github.com/carpentries/carpentrycon/files/2022796/HPCCarpentry_Comparison.pdf)

**Comment by aturner-epcc** [comment]
I could turn it into a Google doc and link and then people would be able to comment/modify? What do people think?

**Comment by jstaf** [comment]
Touching base on this just now - I think @psteinb 's  solution for creating materials for alternate schedulers/environment module systems/etc. is a great one. Perhaps create a couple different templates for each scheduler as a starting point, and then people could fork the repository and specify a scheduler in `_config.yml` and have it create a nice set of materials for their system? (They could then customize things further, if so desired.)

It might almost be easier to create complete sections on a topic and then swap those out section-by-section. As it stands now, the [Using a scheduler](https://hpc-carpentry.github.io/hpc-intro/12-scheduler/) and [Environment modules](https://hpc-carpentry.github.io/hpc-intro/13-modules/) lessons from the [hpc-intro](https://hpc-carpentry.github.io/hpc-intro/) lesson are completely stand-alone and independent. It would be pretty easy to create a new section for other schedulers/etc, then have jekyll swap out the files in the table of contents based on a value `_config.yml`. Anyhow just throwing out ideas here, I think @psteinb 's idea to use Jekyll here is a good one.

(Can't make the session unfortunately, but let me know what happens!)

**Pull request merged**
