### PR TITLE
Adding minutes from 2019-03-05 ccTF meeting

### PR DESCRIPTION
**Pull request by sstevens2**
Please feel free to let me know if there is anything that needs to be updated in the minutes! 😄

### CODE REVIEW

**Comment by fpsom** [comment]
Thanks @sstevens2 !

**Comment by sstevens2** [comment]
Thanks @fpsom!  You were so quick I didn't even get to send my slack message asking who could review this and merge it.

**Comment by fpsom** [comment]
Oups... sorry! I was on GitHub and got the notification. Next time I'll ask first before merging...

**Comment by sstevens2** [comment]
Sorry for the miss communication @fpsom, that wasn't meant to be a complaint but rather a complement!  I was happy you merged it and impressed with how quickly you had done it.

**Comment by fpsom** [comment]
No worries, all good! As you can see, I'm constantly lurking on GitHub...  :)

**Pull request merged**
